### ISSUE TITLE
Sketch 47 - High Sierra

### ISSUE THREAD

**Issue by iamsankalp** [kylehickinson/Sketch-SF-UI-Font-Fixer#13]
Don't think it's working. After selecting text layers and selecting plugin to run, nothing changes. Can someone verify if it's working for them?

I'm using for SF Pro typefaces.

Sankalp

**Comment by kylehickinson** [comment]
Seems like there's an issue with Sketch 47 and the conventional method of adjusting the character spacing.. I'll take a look :)

In the meantime, feel free to try the [framework-testing](https://github.com/kylehickinson/Sketch-SF-UI-Font-Fixer/tree/framework-testing) branch, which I've confirmed working. It loads a framework at Sketch launch and handles everything automatically instead of having to run the plugin each time.

**Comment by kylehickinson** [comment]
Sorry I was using an old version of my old plugin when I tested lol.  I confirmed it works in Sketch 47 on Sierra.  I'll check on High Sierra tonight but it seems like everything works fine.

**Comment by iamsankalp** [comment]
Thanks for getting back, @kylehickinson! I tested `framework-testing` on High Sierra Beta. Working perfectly fine.
