### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ivancucer** [kylehickinson/Sketch-SF-UI-Font-Fixer#2]
Hello,

OS X 10.11 -> Sketch 3.3.3 -> Text Layer -> Nothing :)

Best,
Ivan

**Comment by kylehickinson** [comment]
Just tested this on OS X 10.11, Sketch 3.3.3 on a text layer of 40 points using SF UI Display and it worked.
- Are your text layers using the correct font? (SF UI Text for < 20pt, SF UI Display for >= 20 pt). Using SF UI Text on a layer which is greater than 20 points won't switch it over. Although maybe its a good idea for me to add a check for that and maybe swap the font through the plugin.
- Are your San Francisco fonts official ([download here](http://developer.apple.com/fonts/)). If they are not, chances are they don't have the proper font postscript name that the plugin is checking for

**Comment by ivancucer** [comment]
Hey Kyle,

Thank you for your reply. So I downloaded fonts from here https://designcode.io/ios9 I will download ones from the official website in case just to test. Well I have a text layer -> SF UI Text / Regular / 12 and I apply your plugin and nothing changed :)

Best,
Ivan

**Comment by dlukichev** [comment]
Hey Kyle,

Thank you for your plugin, it really helps! 

Probably I know why **ivancucer** have a problem.

The problem I faced while working with your plugin is that I usually design all screens in 1x size for retina displays (750x1334 for iPhone6) so all font sizes in my layouts are 2x. For spacing I use only those sizes that I highlighted in the attached file. Most iOS9 templates has 1x retina screens and most people use it, because u can mirror your iPhone with Sketch and see live results that fits the phone. It would be very cool if you have different plugins for retina and non-retina.

Thank you again!
Cheers, Dmitrii

![image](https://cloud.githubusercontent.com/assets/16936463/12642963/1e702566-c5ca-11e5-95e6-5a57463415d7.png)
